libpaxos-cpp: paxos::detail::protocol::basic_paxos Class Reference
paxos::detail::protocol::basic_paxos Class Reference
Implementation of the basic_paxos algorithm.
#include <basic_paxos.hpp>
Classes
struct state
Public Types
typedef boost::function< void(boost::optional
< enum paxos::error_code >
, std::string const &)> client_callback_type
Public Member Functions
basic_paxos (detail::protocol::protocol &protocol)
Constructor.
void start (tcp_connection::pointer client_connection, command const &command)
Starts basic_paxos with all nodes in quorum.
void receive_prepare (tcp_connection::pointer connection, command const &command)
Received by a follower when a leader wants to prepare a request.
void receive_accept (tcp_connection::pointer connection, command const &command)
Received by a follower when a leader has sent an accept.
Detailed Description
Implementation of the basic_paxos algorithm.
Definition at line 27 of file basic_paxos.hpp.
Constructor & Destructor Documentation
paxos::detail::protocol::basic_paxos::basic_paxos (detail::protocol::protocol & protocol)
Constructor.
Parameters
protocol Reference to the protocol we live in
Definition at line 9 of file basic_paxos.cpp.
Member Function Documentation
void paxos::detail::protocol::basic_paxos::receive_accept (tcp_connection::pointer connection, command const & command)
Received by a follower when a leader has sent an accept.
Parameters
connection Connection with the leader
command Command received by the follower
Definition at line 249 of file basic_paxos.cpp.
References paxos::detail::protocol::protocol::process_workload(), paxos::detail::command::type_request_accepted, and paxos::detail::protocol::protocol::write_command().
void paxos::detail::protocol::basic_paxos::receive_prepare (tcp_connection::pointer connection, command const & command)
Received by a follower when a leader wants to prepare a request.
Parameters
connection Connection with the leader
command Command received by the follower
Definition at line 99 of file basic_paxos.cpp.
References paxos::detail::protocol::protocol::quorum(), paxos::detail::command::type_request_fail, paxos::detail::command::type_request_promise, and paxos::detail::protocol::protocol::write_command().
void paxos::detail::protocol::basic_paxos::start (tcp_connection::pointer client_connection, command const & command)
Starts basic_paxos with all nodes in quorum.
Parameters
client_connection Connection with the client that initiated the request
command Command received by the client
callback Callback we can override
Definition at line 18 of file basic_paxos.cpp.
References paxos::detail::protocol::protocol::quorum().
The documentation for this class was generated from the following files:
paxos++/detail/protocol/basic_paxos.hpp
paxos++/detail/protocol/basic_paxos.cpp