libpaxos-cpp: paxos::detail::strategies::basic_paxos::protocol::request Class Reference
paxos::detail::strategies::basic_paxos::protocol::request Class Reference
Defines protocol used when a leader must propagate a request throughout the quorum.
#include <request.hpp>
Classes
struct state
Static Public Member Functions
static void step1 (tcp_connection::pointer client_connection, detail::command const &command, detail::quorum::quorum &quorum, detail::paxos_state &state)
Received by leader from client that initiates a request.
static void step3 (tcp_connection::pointer leader_connection, detail::command const &command, detail::quorum::quorum &quorum, detail::paxos_state &state)
Received by follower when leader wants to prepare a request.
static void step6 (tcp_connection::pointer leader_connection, detail::command const &command, detail::quorum::quorum &quorum, detail::paxos_state &state)
Received by follower when leader wants to process a request.
Detailed Description
Defines protocol used when a leader must propagate a request throughout the quorum.
Definition at line 26 of file request.hpp.
Member Function Documentation
void paxos::detail::strategies::basic_paxos::protocol::request::step1 (tcp_connection::pointer client_connection, detail::command const & command, detail::quorum::quorum & quorum, detail::paxos_state & proposal_id) static
Received by leader from client that initiates a request.
static
Definition at line 11 of file request.cpp.
References paxos::detail::quorum::quorum::live_servers(), paxos::detail::quorum::quorum::our_endpoint(), and paxos::detail::quorum::quorum::our_leader().
void paxos::detail::strategies::basic_paxos::protocol::request::step3 (tcp_connection::pointer leader_connection, detail::command const & command, detail::quorum::quorum & quorum, detail::paxos_state & state) static
Received by follower when leader wants to prepare a request.
static
Definition at line 95 of file request.cpp.
References paxos::detail::quorum::quorum::our_endpoint(), paxos::detail::command::type_request_fail, paxos::detail::command::type_request_promise, and paxos::detail::parser::write_command().
void paxos::detail::strategies::basic_paxos::protocol::request::step6 (tcp_connection::pointer leader_connection, detail::command const & command, detail::quorum::quorum & quorum, detail::paxos_state & state) static
Received by follower when leader wants to process a request.
This request is received by a follower when a leader has received an 'ACK' for a certain proposal id from all followers, and is now telling all followers to actually process a command.
static
Definition at line 244 of file request.cpp.
References paxos::detail::command::type_request_accepted, and paxos::detail::parser::write_command().
The documentation for this class was generated from the following files:
paxos++/detail/strategies/basic_paxos/protocol/request.hpp
paxos++/detail/strategies/basic_paxos/protocol/request.cpp