libpaxos-cpp: paxos::detail::quorum::quorum Class Reference
paxos::detail::quorum::quorum Class Reference
Represents the quorum and provides interface to utility funcitons.
#include <quorum.hpp>
Public Member Functions
quorum (boost::asio::io_service &io_service)
Constructor for clients.
quorum (boost::asio::io_service &io_service, boost::asio::ip::tcp::endpoint const &endpoint)
void reset ()
Resets our state completely.
void new_leader (boost::asio::ip::tcp::endpoint const &endpoint)
Called when a new leader is announced.
boost::asio::ip::tcp::endpoint
const & our_endpoint () const
Access to our own endpoint, so we can identify ourselves.
bool we_have_our_endpoint () const
Determines whether an endpoint was registered.
enum server::state our_state () const
Based on our_endpoint (), looks up the state we currently have.
void set_host_state (boost::asio::ip::tcp::endpoint const &server, enum server::state state)
Based on endpoint, adjusts a server's state.
boost::uuids::uuid const & our_id () const
Based on our_endpoint (), looks up our host's id.
void set_host_id (boost::asio::ip::tcp::endpoint const &server, boost::uuids::uuid const &id)
Based on endpoint, adjusts a server's unique identifier.
boost::asio::ip::tcp::endpoint who_should_be_leader () const
Returns the endpoint of the host within our quorum we think should be a leader.
bool we_have_a_leader () const
Returns true if we have one leader in the quorum.
boost::asio::ip::tcp::endpoint
const & our_leader () const
Returns endpoint of the current leader of the quorum.
tcp_connection::pointer our_leader_connection () const
Returns our leader's tcp_connection.
std::vector< server > live_servers () const
Provides access to all connections to all "live" nodes.
void bootstrap ()
Basically a forward to heartbeat ()
void add (boost::asio::ip::tcp::endpoint const &endpoint)
Adds new node to the quorum.
void mark_dead (boost::asio::ip::tcp::endpoint const &endpoint)
Resets server to a 'dead' state.
void connection_established (boost::asio::ip::tcp::endpoint const &endpoint, tcp_connection::pointer connection)
Called when a connection has been established with a server.
Detailed Description
Represents the quorum and provides interface to utility funcitons.
Definition at line 26 of file quorum.hpp.
Constructor & Destructor Documentation
paxos::detail::quorum::quorum::quorum (boost::asio::io_service & io_service)
Constructor for clients.
Parameters
io_service References the OS'es underlying I/O services
This constructor assumes we are not part of the quorum.
Definition at line 14 of file quorum.cpp.
Member Function Documentation
void paxos::detail::quorum::quorum::bootstrap ()
Basically a forward to heartbeat ()
We can simply forward this to heartbeat since that will automatically establish connections / handshakes with hosts in recovery mode.
Definition at line 319 of file quorum.cpp.
std::vector< server > paxos::detail::quorum::quorum::live_servers () const
Provides access to all connections to all "live" nodes.
This function is useful for when messages need to be broadcasted to all nodes within the quorum.
Definition at line 287 of file quorum.cpp.
References paxos::detail::quorum::server::state_client, paxos::detail::quorum::server::state_dead, paxos::detail::quorum::server::state_follower, paxos::detail::quorum::server::state_leader, paxos::detail::quorum::server::state_non_participant, and paxos::detail::quorum::server::state_unknown.
void paxos::detail::quorum::quorum::new_leader (boost::asio::ip::tcp::endpoint const & endpoint)
Called when a new leader is announced.
Parameters
endpoint Endpoint of the host that is the new leader
Definition at line 72 of file quorum.cpp.
References our_endpoint(), paxos::detail::quorum::server::set_state(), paxos::detail::quorum::server::state_follower, and paxos::detail::quorum::server::state_leader.
boost::asio::ip::tcp::endpoint const & paxos::detail::quorum::quorum::our_endpoint () const
Access to our own endpoint, so we can identify ourselves.
Precondition
we_have_our_endpoint () == true
Definition at line 92 of file quorum.cpp.
References we_have_our_endpoint().
boost::asio::ip::tcp::endpoint const & paxos::detail::quorum::quorum::our_leader () const
Returns endpoint of the current leader of the quorum.
Precondition
we_have_a_leader () == true
Definition at line 265 of file quorum.cpp.
References paxos::detail::quorum::server::state_leader, and we_have_a_leader().
tcp_connection::pointer paxos::detail::quorum::quorum::our_leader_connection () const
Returns our leader's tcp_connection.
Precondition
we_have_a_leader () == true
Definition at line 281 of file quorum.cpp.
References paxos::detail::quorum::server::connection(), and our_leader().
void paxos::detail::quorum::quorum::reset ()
Resets our state completely.
This function is called when some quorum inconsistency is detected between multiple hosts, and this resets the state of all hosts to 'unknown', except our own entry, which is set to 'non_participant'.
Definition at line 54 of file quorum.cpp.
References our_endpoint(), paxos::detail::quorum::server::state_non_participant, and paxos::detail::quorum::server::state_unknown.
The documentation for this class was generated from the following files:
paxos++/detail/quorum/quorum.hpp
paxos++/detail/quorum/quorum.cpp