libpaxos-cpp: paxos::detail::dispatcher Class Reference
paxos::detail::dispatcher Class Reference
Ensures that commands are dispatched to the proper handler.
#include <dispatcher.hpp>
Static Public Member Functions
static void dispatch_command (tcp_connection::pointer connection, detail::command const &command, detail::quorum::quorum &quorum, detail::paxos_state &state)
Dispatches command to the appropriate handler.
Detailed Description
Ensures that commands are dispatched to the proper handler.
Definition at line 24 of file dispatcher.hpp.
Member Function Documentation
void paxos::detail::dispatcher::dispatch_command (tcp_connection::pointer connection, detail::command const & command, detail::quorum::quorum & quorum, detail::paxos_state & state) static
Dispatches command to the appropriate handler.
Parameters
connection Connection that received this command
command The command that was received
quorum Reference to our server's current quorum
state Keeps track of state information for various paxos strategies
static
Definition at line 15 of file dispatcher.cpp.
References paxos::detail::strategies::basic_paxos::protocol::request::step1(), paxos::detail::quorum::protocol::announce_leadership::step2(), paxos::detail::quorum::protocol::handshake::step2(), paxos::detail::strategies::basic_paxos::protocol::request::step3(), paxos::detail::strategies::basic_paxos::protocol::request::step6(), paxos::detail::command::type_handshake_start, paxos::detail::command::type_leader_claim, paxos::detail::command::type_request_accept, paxos::detail::command::type_request_initiate, and paxos::detail::command::type_request_prepare.
The documentation for this class was generated from the following files:
paxos++/detail/dispatcher.hpp
paxos++/detail/dispatcher.cpp