libpaxos-cpp: paxos::detail::quorum::protocol::announce_leadership Class Reference
paxos::detail::quorum::protocol::announce_leadership Class Reference
Defines protocol used when a leader announces rulership over a quorum.
#include <announce_leadership.hpp>
Static Public Member Functions
static void step1 (boost::asio::io_service &io_service, tcp_connection::pointer connection, detail::quorum::quorum &quorum)
Announce our leadership to another host.
static void step2 (tcp_connection::pointer connection, detail::command const &command, detail::quorum::quorum &quorum)
Entry point when a announce_leadership has been received.
Detailed Description
Defines protocol used when a leader announces rulership over a quorum.
Definition at line 29 of file announce_leadership.hpp.
Member Function Documentation
void paxos::detail::quorum::protocol::announce_leadership::step1 (boost::asio::io_service & io_service, tcp_connection::pointer connection, detail::quorum::quorum & quorum) static
Announce our leadership to another host.
Parameters
io_service Interface to the OS'es underlying I/O functions
connection Connection to the host we're shaking hands with
quorum Quorum to store the host's details in
static
Definition at line 11 of file announce_leadership.cpp.
References paxos::detail::quorum::quorum::our_endpoint(), paxos::detail::quorum::quorum::our_id(), paxos::detail::quorum::quorum::our_state(), paxos::detail::quorum::server::state_client, paxos::detail::command::type_leader_claim, paxos::detail::quorum::quorum::who_should_be_leader(), and paxos::detail::parser::write_command().
void paxos::detail::quorum::protocol::announce_leadership::step2 (tcp_connection::pointer connection, detail::command const & command, detail::quorum::quorum & quorum) static
Entry point when a announce_leadership has been received.
static
Definition at line 45 of file announce_leadership.cpp.
References paxos::detail::quorum::quorum::new_leader(), paxos::detail::quorum::quorum::reset(), and paxos::detail::quorum::quorum::who_should_be_leader().
The documentation for this class was generated from the following files:
paxos++/detail/quorum/protocol/announce_leadership.hpp
paxos++/detail/quorum/protocol/announce_leadership.cpp