libpaxos-cpp: paxos::detail::protocol::pb::command Class Reference
paxos::detail::protocol::pb::command Class Reference
#include <command.pb.h>
Public Member Functions
command ()
virtual ~command ()
command (const command &from)
command & operator= (const command &from)
const
::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (command *other)
command * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const command &from)
void MergeFrom (const command &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
bool has_type () const
void clear_type ()
paxos::detail::protocol::pb::command_type type () const
void set_type (paxos::detail::protocol::pb::command_type value)
bool has_host_id () const
void clear_host_id ()
const ::std::string & host_id () const
void set_host_id (const ::std::string &value)
void set_host_id (const char *value)
void set_host_id (const char *value, size_t size)
inline::std::string * mutable_host_id ()
Static Public Member Functions
static const
::google::protobuf::Descriptor * descriptor ()
static const command & default_instance ()
Static Public Attributes
static const int kTypeFieldNumber = 1
static const int kHostIdFieldNumber = 2
Friends
void protobuf_AddDesc_paxos_2b_2b_2fdetail_2fprotocol_2fpb_2fcommand_2eproto ()
void protobuf_AssignDesc_paxos_2b_2b_2fdetail_2fprotocol_2fpb_2fcommand_2eproto ()
void protobuf_ShutdownFile_paxos_2b_2b_2fdetail_2fprotocol_2fpb_2fcommand_2eproto ()
Detailed Description
Definition at line 62 of file command.pb.h.
Constructor & Destructor Documentation
paxos::detail::protocol::pb::command::command ()
Definition at line 125 of file command.pb.cc.
paxos::detail::protocol::pb::command::~command () [virtual]
Definition at line 146 of file command.pb.cc.
paxos::detail::protocol::pb::command::command (const command & from)
Definition at line 133 of file command.pb.cc.
References MergeFrom().
Member Function Documentation
int paxos::detail::protocol::pb::command::ByteSize () const
Definition at line 298 of file command.pb.cc.
References has_host_id(), has_type(), host_id(), type(), and unknown_fields().
void paxos::detail::protocol::pb::command::Clear ()
Definition at line 178 of file command.pb.cc.
References mutable_unknown_fields().
void paxos::detail::protocol::pb::command::clear_host_id () [inline]
Definition at line 189 of file command.pb.h.
void paxos::detail::protocol::pb::command::clear_type () [inline]
Definition at line 172 of file command.pb.h.
void paxos::detail::protocol::pb::command::CopyFrom (const command & from)
Definition at line 358 of file command.pb.cc.
References Clear(), and MergeFrom().
void paxos::detail::protocol::pb::command::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 352 of file command.pb.cc.
References Clear(), and MergeFrom().
const command & paxos::detail::protocol::pb::command::default_instance () [static]
Definition at line 168 of file command.pb.cc.
References protobuf_AddDesc_paxos_2b_2b_2fdetail_2fprotocol_2fpb_2fcommand_2eproto.
const ::google::protobuf::Descriptor * paxos::detail::protocol::pb::command::descriptor () [static]
Definition at line 163 of file command.pb.cc.
int paxos::detail::protocol::pb::command::GetCachedSize () const [inline]
Definition at line 103 of file command.pb.h.
google::protobuf::Metadata paxos::detail::protocol::pb::command::GetMetadata () const
Definition at line 379 of file command.pb.cc.
bool paxos::detail::protocol::pb::command::has_host_id () const [inline]
Definition at line 186 of file command.pb.h.
bool paxos::detail::protocol::pb::command::has_type () const [inline]
Definition at line 169 of file command.pb.h.
const ::std::string & paxos::detail::protocol::pb::command::host_id () const [inline]
Definition at line 195 of file command.pb.h.
bool paxos::detail::protocol::pb::command::IsInitialized () const
Definition at line 364 of file command.pb.cc.
void paxos::detail::protocol::pb::command::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 327 of file command.pb.cc.
void paxos::detail::protocol::pb::command::MergeFrom (const command & from)
Definition at line 339 of file command.pb.cc.
References host_id(), mutable_unknown_fields(), set_host_id(), set_type(), type(), and unknown_fields().
bool paxos::detail::protocol::pb::command::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 191 of file command.pb.cc.
References paxos::detail::protocol::pb::command_type_IsValid(), DO_, host_id(), mutable_host_id(), mutable_unknown_fields(), and set_type().
std::string * paxos::detail::protocol::pb::command::mutable_host_id () [inline]
Definition at line 219 of file command.pb.h.
inline ::google::protobuf::UnknownFieldSet* paxos::detail::protocol::pb::command::mutable_unknown_fields () [inline]
Definition at line 78 of file command.pb.h.
command * paxos::detail::protocol::pb::command::New () const
Definition at line 174 of file command.pb.cc.
command& paxos::detail::protocol::pb::command::operator= (const command & from) [inline]
Definition at line 69 of file command.pb.h.
References CopyFrom().
void paxos::detail::protocol::pb::command::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 250 of file command.pb.cc.
References host_id(), type(), and unknown_fields().
google::protobuf::uint8 * paxos::detail::protocol::pb::command::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 273 of file command.pb.cc.
References host_id(), type(), and unknown_fields().
void paxos::detail::protocol::pb::command::set_host_id (const ::std::string & value) [inline]
Definition at line 198 of file command.pb.h.
void paxos::detail::protocol::pb::command::set_host_id (const char * value) [inline]
Definition at line 205 of file command.pb.h.
void paxos::detail::protocol::pb::command::set_host_id (const char * value, size_t size) [inline]
Definition at line 212 of file command.pb.h.
void paxos::detail::protocol::pb::command::set_type (paxos::detail::protocol::pb::command_type value) [inline]
Definition at line 179 of file command.pb.h.
References paxos::detail::protocol::pb::command_type_IsValid().
void paxos::detail::protocol::pb::command::Swap (command * other)
Definition at line 369 of file command.pb.cc.
paxos::detail::protocol::pb::command_type paxos::detail::protocol::pb::command::type () const [inline]
Definition at line 176 of file command.pb.h.
const ::google::protobuf::UnknownFieldSet& paxos::detail::protocol::pb::command::unknown_fields () const [inline]
Definition at line 74 of file command.pb.h.
Friends And Related Function Documentation
void protobuf_AddDesc_paxos_2b_2b_2fdetail_2fprotocol_2fpb_2fcommand_2eproto () [friend]
void protobuf_AssignDesc_paxos_2b_2b_2fdetail_2fprotocol_2fpb_2fcommand_2eproto () [friend]
void protobuf_ShutdownFile_paxos_2b_2b_2fdetail_2fprotocol_2fpb_2fcommand_2eproto () [friend]
Member Data Documentation
const int paxos::detail::protocol::pb::command::kHostIdFieldNumber = 2 [static]
Definition at line 126 of file command.pb.h.
const int paxos::detail::protocol::pb::command::kTypeFieldNumber = 1 [static]
Definition at line 119 of file command.pb.h.
The documentation for this class was generated from the following files:
paxos++/detail/protocol/pb/command.pb.h
paxos++/detail/protocol/pb/command.pb.cc